config/routes.rb
Waf::Application.routes.draw do
  resources :blanks

  get "site/home"
  get "site/about"
  get "site/weather"
  get "site/gallery"
match '/about' => 'site#about'
match '/home' => 'home#home'
match '/gallery' => 'site#gallery'
match 'home/location' => 'home#myMethod'
match '/weather' => 'site#weather'

  root :to => 'site#home'

end

app/models/blank.rb
class Blank < ActiveRecord::Base
  attr_accessible :notneeded
end

app/models/calc.rb
require 'ierail'
require 'json'
module DanStuff

	def self.setupLoc(lat1, long1)
		@lat = lat1
		@long = long1
	  	# set min as an instance variable using @
	  	@min = 9999999999
	  	# create an instance variable to hold the station name
	  	@station = nil	
		self.getStation
	end

	def self.getStation
		ir = IERail.new
	  	trainStations = ir.stations
		hash = {}
	for code in trainStations do 
		hash[code.description]=code.location
	end	
	#puts hash
		#stations = { 
  #'Pearse' => [53.343160, -6.247490],
  #'Tara Street' => [53.347070, -6.253980],
  #'Dublin Connolly' => [53.351361, -6.250067],
  #'Clontarf Road' => [53.362897, -6227767],
  #'Killester' => [53.372762, -6.205333],
  #'Harmonstown' => [53.378554, -6.192266],
  #'Raheny' => [53.381485, -6177020]
#}
	
	 hash.each do |station,coords|
	#	puts station
   # distance is = to hte result of the haversine with the following coords taken in
    distance = haversine(@lat,@long,coords[1].to_f,coords[0].to_f)
   # if distance is less than the set @min then replace @min with the new distance
    if distance < @min
      @min = distance
      @station = station#, coords[1],coords[0]
	@coords = coords[1]
	@coords2= coords[0]
    end
	#puts "#{@lat} #{@long} #{coords[1]} #{coords[0]}" 
  end
  #############################
	times = ir.station_times(@station.to_s,30)
	 timesHash = Hash.new
	#test = ir.stations
	
	for code in times do 
#timesHash[code.traincode]=code.origin,code.destination, code.train_type ,code.duein ,code.last_location
		timesHash={:traincode => code.traincode, :traintype => code.train_type, :duein => code.duein, :lastlocation => code.last_location, :direction => code.direction}
		#, :origin => code.origin, :destination => code.destination_time
	
	end
	@times = timesHash
	puts "load #{@times.to_json}"
	#puts "load #{times}"
	#puts "load #{timesHash}"
  #############################
	return @station, @coords , @coords2
	#return @times
	end

  def self.haversine(lat1, long1, lat2, long2)
    dtor = Math::PI/180
    r = 6378.14*1000
	#puts  "The values are #{lat1}, #{long1}, #{lat2}, #{long2}"
    rlat1 = lat1*dtor
 	rlong1 = long1*dtor
  	rlat2 = lat2*dtor
   	rlong2 = long2*dtor

	dlon = rlong1 - rlong2
	dlat = rlat1 - rlat2

  	a = power(Math::sin(dlat/2), 2) + Math::cos(rlat1)*Math::cos(rlat2)*power(Math::sin(dlon/2), 2)
   	c = 2*Math::atan2(Math::sqrt(a), Math::sqrt(1-a))
	d = r*c
	d
  end

  def self.power(num, pow)
    num ** pow
  end
end
ouput = DanStuff.setupLoc(53.33005285530366, -6.25946044921875)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blanks_controller.rb
class BlanksController < ApplicationController
  # GET /blanks
  # GET /blanks.json
  def index
    @blanks = Blank.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blanks }
    end
  end

  # GET /blanks/1
  # GET /blanks/1.json
  def show
    @blank = Blank.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blank }
    end
  end

  # GET /blanks/new
  # GET /blanks/new.json
  def new
    @blank = Blank.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blank }
    end
  end

  # GET /blanks/1/edit
  def edit
    @blank = Blank.find(params[:id])
  end

  # POST /blanks
  # POST /blanks.json
  def create
    @blank = Blank.new(params[:blank])

    respond_to do |format|
      if @blank.save
        format.html { redirect_to @blank, notice: 'Blank was successfully created.' }
        format.json { render json: @blank, status: :created, location: @blank }
      else
        format.html { render action: "new" }
        format.json { render json: @blank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blanks/1
  # PUT /blanks/1.json
  def update
    @blank = Blank.find(params[:id])

    respond_to do |format|
      if @blank.update_attributes(params[:blank])
        format.html { redirect_to @blank, notice: 'Blank was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blanks/1
  # DELETE /blanks/1.json
  def destroy
    @blank = Blank.find(params[:id])
    @blank.destroy

    respond_to do |format|
      format.html { redirect_to blanks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
	#client = Weatherman::Client.new	 
	#response= client.lookup_by_woeid('560743')
	#@location=response.location['city']
	#@temp = response.condition['temp']
	#@forecast= response.atmosphere['humidity']
	#@weather = response.condition['text']
	
  end
def myMethod
	#distance = receivedJSON[:lat]
	receivedJSON= params[:location]
	@lat = receivedJSON[:lat]
	@long =	receivedJSON[:long]
	trainTimes = RailCalc.setupLoc(@lat, @long)
	#trainTimes
	newJSON = "{\"response\" : { \"StationName\": \"#{trainTimes[0]}\", \"Lat\":\"#{trainTimes[1]}\" ,\"Long\":\"#{trainTimes[2]}\"}}"
	#, \"Times\":\"#{trainTimes[3]}\"
	#newJSON = "{\"response\" : #{trainTimes[3].to_json}}"
	render json: newJSON	
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def about
  end

  def contact
  end

  def weather
	client = Weatherman::Client.new	 
	response= client.lookup_by_woeid('560743')
	@location=response.location['city']
	@temp = response.condition['temp']
	@forecast= response.condition['forecast']
	@weather = response.condition['text']

	response2= client.lookup_by_woeid('560472')
	@loc2=response2.location['city']
	@te = response2.condition['temp']
	@fore= response2.condition['forecast']
	@weath = response2.condition['text']

	response3= client.lookup_by_woeid('560912')
	@location3=response3.location['city']
	@temp3 = response3.condition['temp']
	@forecast3= response3.condition['forecast']
	@weather3 = response3.condition['text']

	response4= client.lookup_by_woeid('562245')
	@location4=response4.location['city']
	@temp4 = response4.condition['temp']
	@forecast4= response4.condition['forecast']
	@weather4 = response4.condition['text']
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blanks_helper.rb
module BlanksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/blanks/_form.html.erb
<%= form_for(@blank) do |f| %>
  <% if @blank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blank.errors.count, "error") %> prohibited this blank from being saved:</h2>

      <ul>
      <% @blank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notneeded %><br />
    <%= f.text_field :notneeded %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blanks/edit.html.erb
<h1>Editing blank</h1>

<%= render 'form' %>

<%= link_to 'Show', @blank %> |
<%= link_to 'Back', blanks_path %>

app/views/blanks/index.html.erb
<h1>Listing blanks</h1>

<table>
  <tr>
    <th>Notneeded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blanks.each do |blank| %>
  <tr>
    <td><%= blank.notneeded %></td>
    <td><%= link_to 'Show', blank %></td>
    <td><%= link_to 'Edit', edit_blank_path(blank) %></td>
    <td><%= link_to 'Destroy', blank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blank', new_blank_path %>

app/views/blanks/new.html.erb
<h1>New blank</h1>

<%= render 'form' %>

<%= link_to 'Back', blanks_path %>

app/views/blanks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Notneeded:</b>
  <%= @blank.notneeded %>
</p>


<%= link_to 'Edit', edit_blank_path(@blank) %> |
<%= link_to 'Back', blanks_path %>

app/views/home/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NoStop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
 <style type="text/css">
        #map_canvas {height:400px;width:600px}
    </style>
    
	
  
    <!-- Le styles -->
    <link href="assets/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="assets/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body onload="initMap()">
    <div class="container-narrow">
	
      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="/home">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/gallery">Gallery</a></li>
	   <li><a href="/weather">Weather</a></li>
        </ul>
        <h3 class="muted">NoStop</h3>
      </div>
      <hr>	
		
		
     <div id="map_canvas"></div>
	
<br />
	<input type="text" id="LocationClicked" value="Location Clicked">
	<input type="text" id="latFld">
	<input type="text" id="lngFld">  
	<input type="text" id="Station">
	<input type="text" id="StationlatFld">
	<input type="text" id="StationlngFld">		
	    
      <hr>
      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="assets/jquery.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>
        var map;
        var markersArray = [];
	var lat
	var myLatlng;
	var marker2
	var long
        function initMap()
        {
            var latlng = new google.maps.LatLng(53.337433437129675, -6.280059814453125);
            var myOptions = {
                zoom: 10,
                center: latlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
	function placeMarker2(location) {
            // add a click event handler to the map object
		marker2 = new google.maps.Marker({
                position: myLatlng,
                map: map
            });
		markersArray.push(marker2);
		}
            google.maps.event.addListener(map, "click", function(event)
            {
                // place a marker
                placeMarker(event.latLng);

                // display the lat/lng in your form's lat/lng fields
		document.getElementById("latFld").value = event.latLng.lat();
                document.getElementById("lngFld").value = event.latLng.lng();
		 lat= event.latLng.lat();
		 long= event.latLng.lng();
				
                        
               
		//'page': { 'lat': lat, 'long': long
		$.ajax({
		    url: 'http://127.0.0.1:3000/home/location',
		    type: 'POST',
		    contentType: 'application/json',
		    data: JSON.stringify({ 'location': { 'lat': lat, 'long': long}}),
		    dataType: 'json',
			success: function(data){
		
			console.log(data.response.name);
			 myLatlng = new google.maps.LatLng(data.response.Lat,data.response.Long);
			 placeMarker2();
			alert('Your nearest station is '+data.response.StationName)
			document.getElementById("StationlatFld").value = data.response.Lat;
                	document.getElementById("StationlngFld").value = data.response.Long;
			document.getElementById("Station").value = data.response.StationName;
			//alert(data.response.StationName.Lat);
		
		},
	error: function (XMLHttpRequest, textStatus, errorThrown) {
            if (textStatus == "Unauthorized") {
               alert('Error: ' + errorThrown);
            }else {
               alert('Error: ' + errorThrown);
		
            }
	}
});

            });
        }
        function placeMarker(location) {
            // first remove all markers if there are any
            deleteOverlays();

            var marker = new google.maps.Marker({
                position: location,
                map: map
            });
		
            // add marker in markers array
            markersArray.push(marker);
	    

            //map.setCenter(location);
        }

        // Deletes all markers in the array by removing references to them
        function deleteOverlays() {
            if (markersArray) {
                for (i in markersArray) {
                    markersArray[i].setMap(null);
                }
            markersArray.length = 0;
            }
        }

                      
    </script>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waf</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="assets/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="assets/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><a href="/home">Home</a></li>
          <li class="active"><a href="/about">About</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
        <h3 class="muted">NoStop</h3>
      </div>

      <hr>

     			<div class="fluid_container">
					<div id="Logo"></div>
					
					
					<div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
					
					<!--Space Slides-->
					
						<div data-src="/assets/header/Ruby.png"></div>
						
						<div data-src="/assets/header/Rail.png"></div>
						<div data-src="/assets/header/rubygems.png"></div>
					
					</div><!--#camera_wrap_1-->
				</div>


      <div class="footer">
        <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />


<p>This web application has been created using the irish rail API and the use of Ruby on Rails and Ruby Gems</p>
     
      </div>

    </div> <!-- /container -->
	
	<div class="container-narrow">
		<hr>
		<div class="footer">
       		<p>&copy; Company 2013</p>
      		</div>
	</div>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="assets/jquery.js"></script>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <script src="/assets/camera.min.js"></script>

    <script src="/assets/jquery.easing.1.3.js"></script>

    <script src="/assets/main.js"></script>
    
    <script>

$(document).ready(function() {

	$(function() {

		$('#camera_wrap_1').camera({

				height: '200px',
				fx: 'stampede',
				playPause: false,
				pagination: false,
				thumbnails: false,
				navigation: true,
				loader: 'none',
				time: 700,
		});
	});
});

</script>




  </body>
</html>

app/views/site/contact.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="assets/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><a href="/home">Home</a></li>
          <li ><a href="/about">About</a></li>
          <li class="active"><a href="/contact">Contact</a></li>
        </ul>
        <h3 class="muted">NoStop</h3>
      </div>

      <hr>
<div class="section" id="example">
	<h2>Examples</h2>

	<h3>Single image</h3>
  <div class="imageRow">
  	<div class="single">
  		<a href="assets/examples/image-1.jpg" rel="lightbox"><img src="assets/examples/thumb-1.jpg" alt="" /></a>
  	</div>
  	<div class="single">
  		<a href="assets/examples/image-2.jpg" rel="lightbox" title="Optional caption."><img src="assets/examples/thumb-2.jpg" alt="" /></a>
  	</div>
  </div>

	<h3 style="clear: both;">Image set</h3>

  <div class="imageRow">
  	<div class="set">
  	  <div class="single first">
  		  <a href="assets/examples/image-3.jpg" rel="lightbox[plants]" title="Click on the right side of the image to move forward."><img src="assets/examples/thumb-3.jpg" alt="Plants: image 1 0f 4 thumb" /></a>
  		</div>
      <div class="single">
  		  <a href="assets/examples/image-4.jpg" rel="lightbox[plants]" title="Alternately you can press the right arrow key." ><img src="assets/examples/thumb-4.jpg" alt="Plants: image 2 0f 4 thumb" /></a>
      </div>
      <div class="single">
  		  <a href="assets/examples/image-5.jpg" rel="lightbox[plants]" title="The script preloads the next image in the set as you're viewing."><img src="assets/examples/thumb-5.jpg" alt="Plants: image 3 0f 4 thumb" /></a>
      </div>
      <div class="single last">
  		  <a href="assets/examples/image-6.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"><img src="assets/examples/thumb-6.jpg" alt="Plants: image 4 0f 4 thumb" /></a>
      </div>
  	</div>
  </div>
	
</div>


      <hr>

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
	<script>
  jQuery(document).ready(function($) {
      $('a').smoothScroll({
        speed: 1000,
        easing: 'easeInOutCubic'
      });

      $('.showOlderChanges').on('click', function(e){
        $('.changelog .old').slideDown('slow');
        $(this).fadeOut();
        e.preventDefault();
      })
  });
</script>


  </body>
</html>

app/views/site/gallery.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="assets/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="assets/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><a href="/home">Home</a></li>
          <li ><a href="/about">About</a></li>
          <li class="active"><a href="/gallery">Gallery</a></li>
	<li><a href="/weather">Weather</a></li>
        </ul>
        <h3 class="muted">NoStop</h3>
      </div>

      <hr>
<div class="section" id="example">
	<h2>Examples</h2>

	<h3>Single image</h3>
  <div class="imageRow">
  	<div class="single">
  		<a href="assets/examples/image-1.jpg" rel="lightbox"><img src="assets/examples/thumb-1.jpg" alt="" /></a>
  	</div>
  	<div class="single">
  		<a href="assets/examples/image-2.jpg" rel="lightbox" title="Optional caption."><img src="assets/examples/thumb-2.jpg" alt="" /></a>
  	</div>
  </div>

	<h3 style="clear: both;">Image set</h3>

  <div class="imageRow">
  	<div class="set">
  	  <div class="single first">
  		  <a href="assets/examples/image-3.jpg" rel="lightbox[plants]" title="Click on the right side of the image to move forward."><img src="assets/examples/thumb-3.jpg" alt="Plants: image 1 0f 4 thumb" /></a>
  		</div>
      <div class="single">
  		  <a href="assets/examples/image-4.jpg" rel="lightbox[plants]" title="Alternately you can press the right arrow key." ><img src="assets/examples/thumb-4.jpg" alt="Plants: image 2 0f 4 thumb" /></a>
      </div>
      <div class="single">
  		  <a href="assets/examples/image-5.jpg" rel="lightbox[plants]" title="The script preloads the next image in the set as you're viewing."><img src="assets/examples/thumb-5.jpg" alt="Plants: image 3 0f 4 thumb" /></a>
      </div>
      <div class="single last">
  		  <a href="assets/examples/image-6.jpg" rel="lightbox[plants]" title="Click the X or anywhere outside the image to close"><img src="assets/examples/thumb-6.jpg" alt="Plants: image 4 0f 4 thumb" /></a>
      </div>
  	</div>
  </div>
	
</div>


      <hr>

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="assets/jquery.js"></script>
	<script>
  jQuery(document).ready(function($) {
      $('a').smoothScroll({
        speed: 1000,
        easing: 'easeInOutCubic'
      });

      $('.showOlderChanges').on('click', function(e){
        $('.changelog .old').slideDown('slow');
        $(this).fadeOut();
        e.preventDefault();
      })
  });
</script>


  </body>
</html>